version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./web_files/:/usr/share/nginx/html
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    restart: on-failure

  python3:
    container_name: python3 
    image: python:3.7.0
    restart: on-failure
    volumes:
      - ./socket/:/usr/src/app
    entrypoint: ["bash", "/usr/src/app/entrypoint.sh"]
    ports:
      - "8765:8765"
    hostname: pondPiServer
