version: '3'

services:
  frontend:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    restart: on-failure
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  backend:
    container_name: python3 
    image: python:3.7.0
    restart: on-failure
    volumes:
      - ./config/entrypoint.sh:/usr/src/app/entrypoint.sh
      - ./config/requirements.txt:/usr/src/app/requirements.txt
      - ./socket:/usr/src/app/
      - ./web_files:/usr/src/app/web_files
    command: ["bash", "/usr/src/app/entrypoint.sh"]
    hostname: pondPiServer
    ports:
      - "8765:8765"
    environment:
      - HTTP_PORT=5002    
      - WEB_SOCKET_PORT=8765
      - WEB_USER=admin
      - WEB_PASS=password
