version: '3'

services:
  frontend:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
      - ./config/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
  backend:
    container_name: python3 
    build: ./socket
    restart: unless-stopped
    volumes:
      - ./config/entrypoint.sh:/usr/src/app/entrypoint.sh
      - ./socket:/usr/src/app/
      - ./web_files:/usr/src/app/web_files
    command: ["bash", "/usr/src/app/entrypoint.sh"]
    hostname: pondPiServer
    ports:
      - "8080:8080"
    environment:
      - HTTP_PORT=5002    
      - WEB_SOCKET_PORT=8080
      - WEB_USER=admin
      - WEB_PASS=password
